baseURL: "https://www.sawyersev.com/"
theme: "up-business-theme"
languageCode: "en-us"
CanonifyURLs: "true"

title: "KAG Foundation"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "KAG Foundation"
  description: "Love people, love God, change the world."
  images:
    - "images/heroes-image.png"

  logo: "arrow-up.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    dribbble: "#"
    instagram: "#"
    facebook: "#"
    twitter: "#"

  location:
    - "Jacksonville, Fl"

  contact:
    - "donate@kag.com"
    - "904.583.0123"

  copyright: "© 2023 Up Business All Rights Reserved"

menus:
  main:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "How we work"
      url: "/#"
      weight: 2

    - name: "Our team"
      url: "/#"
      weight: 3

    - name: "Projects"
      url: "/#"
      weight: 4

    - name: "Blog"
      url: "/blog"
      weight: 5

  buttons:
    - name: "Donate"
      url: "/#"
      weight: 5
      pre: "btn btn-primary text-light"

  footer:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "How we work"
      url: "/#"
      weight: 2

    - name: "Our team"
      url: "/#"
      weight: 3

    - name: "Projects"
      url: "/#"
      weight: 4

    - name: "Blog"
      url: "/blog"
      weight: 5

taxonomies:
  series: "series"
  tags: "tags"
